// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkzzpWwKQ_Nd_JKsuMQwH83NLswvDQMao',
    appId: '1:838256164242:web:218fc7e885b56d68f7554b',
    messagingSenderId: '838256164242',
    projectId: 'auth-4b1fb',
    authDomain: 'auth-4b1fb.firebaseapp.com',
    storageBucket: 'auth-4b1fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO7o9ksUaXX-cAUf4e8tUfThu66WYlm9k',
    appId: '1:838256164242:android:9a008223e6a7105cf7554b',
    messagingSenderId: '838256164242',
    projectId: 'auth-4b1fb',
    storageBucket: 'auth-4b1fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOpe0BZI6hemvqJa5n078C_rUddX3g674',
    appId: '1:838256164242:ios:4c1e1a5c7170ac70f7554b',
    messagingSenderId: '838256164242',
    projectId: 'auth-4b1fb',
    storageBucket: 'auth-4b1fb.appspot.com',
    iosClientId: '838256164242-t1dnf6o1td18ktlvrq8h6losjrfgugk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOpe0BZI6hemvqJa5n078C_rUddX3g674',
    appId: '1:838256164242:ios:4c1e1a5c7170ac70f7554b',
    messagingSenderId: '838256164242',
    projectId: 'auth-4b1fb',
    storageBucket: 'auth-4b1fb.appspot.com',
    iosClientId: '838256164242-t1dnf6o1td18ktlvrq8h6losjrfgugk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinSignup',
  );
}
